version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - update_changelog:
          filters:
            branches:
              only: master

  update_changelog:
      working_directory: ~/build
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - setup_remote_docker:
            version: 17.11.0-ce
        - checkout
        - run:
            name: Update Changelog
            command: |
              cid=$(docker run -d -it ferrarimarco/github-changelog-generator:1.14.3 -u cybercongress -p js-amino --exclude-tags-regex .*[.].*[.].*[.].* --token $DOCS_GITHUB_TOKEN )
              docker attach $cid
              docker cp $cid:/usr/local/src/your-app/CHANGELOG.md ./CHANGELOG.md
              diff=$(git diff CHANGELOG.md)
              if [[  -n  "$diff" ]]; then
                git config --global user.email "cybercongress42@gmail.com"
                git config --global user.name "Cyber Admin"
                git add CHANGELOG.md
                git commit -m "Circle CI: Update Changelog"
                git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/js-amino.git master
              fi
